### ISSUE TITLE
notebook for training results error

### ISSUE THREAD

**Issue by jadhvank** [X3N4/neural_citation#1]
tried ncn_training.ipynb and it shows 1 warning and 1 error message.

Warning
```
/lib/python3.7/site-packages/torch/nn/modules/rnn.py:51: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
```

Error
```
Running on: cuda
Number of model parameters: 24,341,796
Encoders: # Filters = 256, Context filter length = [4, 4, 5, 6, 7],  Context filter length = [1, 2]
Embeddings: Dimension = 128, Pad index = 1, Context vocab = 20002, Author vocab = 20002, Title vocab = 20004
Decoder: # GRU cells = 1, Hidden size = 256
Parameters: Dropout = 0.2, Show attention = False
-------------------------------------------------
TRAINING SETTINGS
Seed = 34, # Epochs = 20, Batch size = 64, Initial lr = 0.001
HBox(children=(IntProgress(value=0, description='Epochs', max=20, style=ProgressStyle(description_width='initial')), HTML(value='')))
HBox(children=(IntProgress(value=0, description='Training batches', max=6280, style=ProgressStyle(description_width='initial')), HTML(value='')))

Traceback (most recent call last):
  File "/tmp/pycharm_project_813/ncn_training.py", line 54, in <module>
    model_name = "embed_128_hid_256_1_GRU")
  File "/tmp/pycharm_project_813/{PRJT_NAME}/training.py", line 225, in train_model
    train_loss = train(model, train_iterator, optimizer, criterion, clip)
  File "/tmp/pycharm_project_813/{PRJT_NAME}/training.py", line 106, in train
    output = model(context = cntxt, title = ttl, authors_citing = citing, authors_cited = cited)
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/pycharm_project_813/{PRJT_NAME}/model.py", line 486, in forward
    encoder_outputs = self.encoder(context, authors_citing, authors_cited)
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/pycharm_project_813/{PRJT_NAME}/model.py", line 185, in forward
    context = self.context_encoder(context)
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/pycharm_project_813/{PRJT_NAME}/model.py", line 105, in forward
    x = [encoder(x) for encoder in self.encoder]
  File "/tmp/pycharm_project_813/{PRJT_NAME}/model.py", line 105, in <listcomp>
    x = [encoder(x) for encoder in self.encoder]
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/tmp/pycharm_project_813/{PRJT_NAME}/model.py", line 61, in forward
    x = F.max_pool2d(x, kernel_size=pool_size)
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "/home/{USER_ID}/.conda/envs/{ENV_NAME}/lib/python3.7/site-packages/torch/nn/functional.py", line 487, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (256x1x38). Calculated output size: (256x0x1). Output size is too small

Process finished with exit code 1
```

warning can be easily solved by change the number of layers but not for error. it seems padding size problem.

**Comment by timoklein** [comment]
Hey,
it should run if you execute the code in the notebook twice.  I think it might be related to some changes between PyTorch 1.1.0 and 1.2.0.
